name: Run Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Show Python version
      run: python --version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip list

    - name: Run tests with verbose output
      run: pytest -v --maxfail=1 --disable-warnings

    - name: Save pytest results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: pytest-results
        path: ./pytest-results/
