name: Run Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Получаем код из репозитория
    - name: Checkout code
      uses: actions/checkout@v3

    # 2️⃣ Устанавливаем Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    # 3️⃣ Проверяем версию Python
    - name: Show Python version
      run: python --version

    # 4️⃣ Устанавливаем зависимости
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip list

    # 5️⃣ Запускаем тесты
    - name: Run pytest
      run: pytest -v --junitxml=main.xml

    # 6️⃣ Сохраняем результаты как артефакт
    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: pytest-results
        path: main.xml
